version: '2'
services:
  cabin_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/focyl"
    restart: always
    ports:
      - 4408:3306
    environment:
      MYSQL_ROOT_PASSWORD: marcos
      MYSQL_DATABASE: focyl
      MYSQL_USER: user
      MYSQL_PASSWORD: marcos
